#!/bin/bash
. /etc/openvpn/script/config.sh

pisoname=`head -n1 $1 | tail -1`

pisopass=`head -n2 $1 | tail -1`


##PREMIUM##
PRE="users.user_name='$pisoname' AND users.auth_vpn='$pisopass' AND users.is_validated=1 AND users.is_freeze=0 AND users.is_active=1 AND users.is_ban=0 AND users.duration > 0"

##VIP##
VIP="users.user_name='$pisoname' AND users.auth_vpn='$pisopass' AND users.is_validated=1 AND users.is_freeze=0 AND users.is_active=1 AND users.is_ban=0 AND users.vip_duration > 0"

##Private##
PRIV="users.user_name='$pisoname' AND users.auth_vpn='$pisopass' AND users.is_validated=1 AND users.is_freeze=0 AND users.is_active=1 AND users.is_ban=0 AND users.private_duration > 0"

Query="SELECT users.user_name FROM users WHERE $PRE OR $VIP OR $PRIV"
user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST --skip-column-name -e "$Query"`

[ "$user_name" != '' ] && [ "$user_name" = "$pisoname" ] && echo "user : $pisoname" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
